defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
      author: "Brent Walther"
      permalink: :title

exclude: [README.md, Gemfile, Gemfile.lock]

# Site settings
title: Brent Walther's Homepage
email: brent@walther.io
description: Brent Walther -- TAMU '14, software engineer, music lover
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brentwalther.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
